# Generated by Django 3.1.5 on 2021-07-11 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/contact')),
                ('full_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.BigIntegerField()),
                ('user_position', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=200)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/deliveryboy')),
                ('full_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.BigIntegerField()),
                ('identity', models.ImageField(blank=True, null=True, upload_to='images/deliveryboy')),
                ('gender', models.CharField(max_length=200)),
                ('locality', models.TextField(max_length=200)),
                ('vehicle', models.TextField(max_length=200)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/product')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('product_weight', models.IntegerField()),
                ('product_color', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_manufacture', models.CharField(max_length=200)),
                ('expirydate', models.DateField()),
                ('manufacture_price', models.IntegerField()),
                ('product_code', models.CharField(max_length=200)),
                ('product_warranty', models.IntegerField()),
                ('query_contact', models.IntegerField()),
                ('product_gurantee', models.IntegerField()),
                ('query_email', models.EmailField(max_length=254)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='taskfile')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('related_to', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('grand_total', models.BigIntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.contact')),
                ('deliveryboy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.deliveryboy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('contact_person', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('czip', models.BigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contractsfile')),
                ('subject', models.CharField(max_length=200)),
                ('contract_value', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=300)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.contact')),
            ],
        ),
    ]
