# Generated by Django 3.1.5 on 2021-07-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='identity',
        ),
    ]
