# Generated by Django 3.1.5 on 2021-07-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_deliveryboy_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='identity',
            field=models.ImageField(blank=True, null=True, upload_to='images/deliveryboy'),
        ),
    ]
