# Generated by Django 3.1.5 on 2021-07-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_deliveryboy_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='images/deliveryboy'),
        ),
    ]
