# Generated by Django 3.1.5 on 2021-07-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0004_auto_20210711_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/profile')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('points', models.BigIntegerField()),
                ('facebook', models.TextField(max_length=500)),
                ('instagram', models.TextField(max_length=500)),
                ('linkedin', models.TextField(max_length=500)),
                ('github', models.TextField(max_length=500)),
                ('about', models.TextField(max_length=1000)),
                ('award1', models.BooleanField(default=False)),
                ('award2', models.BooleanField(default=False)),
                ('award3', models.BooleanField(default=False)),
                ('award4', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=500)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='images/profile/ids')),
                ('designation', models.CharField(max_length=200)),
                ('working_from', models.TimeField()),
                ('working_to', models.TimeField()),
                ('project_id', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
