# Generated by Django 3.1.5 on 2021-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20210713_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
