# Generated by Django 3.1.5 on 2021-07-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20210713_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project_id',
        ),
    ]
