# Generated by Django 3.1.5 on 2021-07-15 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_profile_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.profile'),
            preserve_default=False,
        ),
    ]
