# Generated by Django 3.1.5 on 2021-07-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20210717_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
