# Generated by Django 3.1.5 on 2021-07-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20210718_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='profile_id',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.profile'),
        ),
    ]
