# Generated by Django 3.1.5 on 2021-07-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_auto_20210718_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.profile'),
        ),
    ]
