# Generated by Django 3.1.5 on 2021-07-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20210718_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.profile'),
        ),
    ]
