# Generated by Django 3.1.5 on 2021-07-18 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0018_auto_20210718_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='addedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='addedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='deliveryboy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.deliveryboy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.product'),
            preserve_default=False,
        ),
    ]
