# Generated by Django 3.1.5 on 2021-07-18 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0023_auto_20210718_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='addedby',
            field=models.ForeignKey(blank=True, default=django.db.models.fields.NullBooleanField, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
