# Generated by Django 3.1.5 on 2021-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0028_auto_20210723_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField(blank=True, max_length=500, null=True)),
                ('instagram', models.TextField(blank=True, max_length=500, null=True)),
                ('linkedin', models.TextField(blank=True, max_length=500, null=True)),
                ('github', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
