# Generated by Django 3.1.5 on 2021-07-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0033_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='name',
        ),
    ]
