# Generated by Django 3.1.5 on 2021-07-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_remove_leave_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Purpose',
            new_name='purpose',
        ),
    ]
