# Generated by Django 3.1.5 on 2021-08-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0035_auto_20210729_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='grand_total',
            new_name='our_price',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='product_price',
            new_name='profit',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total',
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_mode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_status',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='quotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.quotations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='vendor',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='vendor_price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
